# Generated by Django 5.2 on 2025-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpage',
            name='user',
        ),
        migrations.AlterField(
            model_name='forumpage',
            name='post',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
